var language_mode;
(function () {
    var x = window.location.href;
    var l = x.slice(-3);
    if (l == "?en") {
        language_mode = "en";
    } else if (l == "?cn") {
        language_mode = "cn";
    } else if (l == "?tp") {
        language_mode = "tp";
    } else if (l == "tml" ) {
        language_mode = "en";
    } else {
        console.log("confused about language input. default is english. ");
        language_mode = "en";
    }
})();
function human_language() {
    return {"light_title": {"cn": "Amoveo 轻钱包",
                            "en": "Amoveo Light Wallet ",
                            "tp": "poki lili pi mani Amoveo"},
            "home_page": {"cn": "主页",
                          "en": "home page ",
                          "tp": "lipu insa"},
            "discuss_on_reddit": {"cn": "在 reddit 上讨论",
                                  "en": "discuss on reddit",
                                  "tp": "kulupu Reddit"},
            "blockchain": {"cn": "区块链",
                           "en": "blockchain ",
                           "tp": "mani sin"},
            "account": {"cn": "帐户",
                        "en": "account ",
                        "tp": "ilo jo mani"},
            "channel": {"cn": "通道",
                        "en": "channel ",
                        "tp": "ilo tu mani"},
            "ip": {"cn": "IP",
                   "en": "IP",
                   "tp": "nanpa suli"},
            "channel_node": {"cn": "通道节点",
                             "en": "channel node",
                             "tp": "jan pi ilo tu mani"},
            "port": {"cn": "端口",
                     "en": "port",
                     "tp": "nanpa lili"},
            "market": {"cn": "市场",
                       "en": "market ",
                       "tp": "esun"},
            "open_order": {"cn": "??",
                           "en": "unmatched order ",
                           "tp": "wile pana"},
            "amount": {"cn": "数量",
                       "en": "amount ",
                       "tp": "mute kama jo"},
            "price": {"cn": "价格",
                      "en": "price ",
                      "tp": "mute kama pana"},
            "amount_send": {"cn": "要发送的数量",
                            "en": "amount to send ",
                            "tp": "mute pana"},
            "spend": {"cn": "发送",
                      "en": "spend",
                      "tp": "pana"},
            "true": {"cn": "真正",//既不是
                     "en": "true ",
                     "tp": "lon"},
            "false": {"cn": "假",//也不是
                      "en": "false ",
                      "tp": "lon ala"},
            "win_if": {"cn": "??",
                       "en": "you win if the outcome is ",
                       "tp": "ni lon la sina jo mute: "},
            "cancel": {"cn": "取消",
                       "en": "cancel ",
                       "tp": "wile ala"},
            "continue": {"cn": "继续",
                         "en": "continue",
                         "tp": "wile"},
            "contract": {"cn": "??",
                         "en": "trade ",
                         "tp": "pana en kama jo"},
            "save_channel": {"cn": "保存通道数据到文件",
                             "en": "save channel data to file",
                             "tp": "o jo ilo tu mani"},
            "channel_state": {"cn": "通道状态",
                              "en": "channel state ",
                              "tp": "toki pi ilo tu mani"},
            "channel_warn": {"cn":"通道状态需要保存!~~~~~~~",
                             "en":"channel state needs to be saved!~~~~~~~~~ ",
                             "tp":"sina wile ala pakala. o jo toki pi ilo tu mani"},
            "save_confirm": {"cn": "通道状态已保存",
                             "en": "channel state is saved.",
                             "tp": "kama pini la sina jo toki pi ilo tu mani"},
            "make_channel": {"cn": "创建通道",
                             "en": "make channel ",
                             "tp": "kama la ilo pi tu mani"},
            "amount_channel": {"cn": "锁定在通道中的数量",
                               "en": "amount to lock in channel ",
                               "tp": "mute pana e ilo pi tu mani"},
            "channel_delay": {"cn": "通道延迟(在区块)",
                              "en": "channel delay (in blocks) ",
                              "tp": "mute tenpo pi pipi e ilo pi tu mani"},
            "unknown": {"cn": "未知",
                        "en": "unknown ",
                        "tp": "sona ala"},
            "your_balance": {"cn": "账户余额",
                             "en": "your balance ",
                             "tp": "sina jo "},
            "check_channel": {"cn": "检查账户余额",
                              "en": "check channel balance",
                              "tp": "o toki e mute jo"},
            "markets": {"cn": "市场",
                        "en": "markets"},
            "markets_link": {"cn": "可以在下边查看可用的市场",
                             "en": "see the available markets here ",
                             "tp": "ni ken lukin e esun mute"},
            "trade_type": {"cn": "贸易类型",
                           "en": "trade type",
                           "tp": "lon ala lon"},
            "make_bet": {"cn": "打个赌",
                         "en": "make bet ",
                         "tp": "??"},
            "finalize_bets": {"cn": "检查是否有赌局已经完成",
                             "en": "check if any bets have been settled"},
            "gather_bets": {"cn": "汇集赌注",
                            "en": "combine bets in opposite directions to recover money from the market "},
            "refresh_bets": {"cn": "更新链下资产余额",
                             "en": "update balance of off-chain assets "},
            "create_account": {"cn": "创建新帐号",
                               "en": "create account "},
            "initial_balance": {"cn": "初始化余额",
                                "en": "initial balance"},
            "more_headers": {"cn": "获取更多的头信息",
                             "en": "get more headers"},
            "height": {"cn": "高度",
                       "en": "height "},
            "total_work": {"cn": "总工作量",
                           "en": "total work"},
            "private_key": {"cn": "私钥",
                            "en": "private key"},
            "save_key": {"cn": "保存私钥到文件",
                         "en": "save private key to file"},
            "get_key": {"cn": "从文件中读取密钥",
                        "en": "get key from file "},
            "make_key": {"cn": "生成新的密钥对",
                         "en": "generate new keys "},
            "check_balance": {"cn": "检查余额",
                              "en": "check balance "},
            "your_pubkey": {"cn": "你的公钥",
                            "en": "your pubkey "},
            "to_pubkey": {"cn": "往公钥地",
                          "en": "to pubkey"},
            "key_warning": {"cn": "这将会删除旧的密钥对. 其中的余额也将被删除",
                            "en": "This will delete your old keys. If money is sent to them, it will be deleted."},
            "stop_mining": {"cn": "停止挖矿",
                            "en": "stop mining"},
            "start_mining": {"cn": "开始挖矿 (注意: 使用电脑或者笔记本, 不要用手机. 想要持续挖矿的话页面不能关闭)",
                             "en": "start mining (warning: use a laptop or computer, not a phone.)(warning: you may need to leave tab open to continue mining.)",
                             "tp": "o alasa mani. "}
           };
}
var language_object = human_language();
function get_words (x) {
    return language_object[x][language_mode];
}
