echo "" > all_txt
cat *.erl >> all_txt
cat */*.erl >> all_txt
cat */*/*.erl >> all_txt
cat */*/*/*.erl >> all_txt
cat */*/*/*/*.erl >> all_txt
cat */*/*/*/*/*.erl >> all_txt
cat */*/*/*/*/*/*.erl >> all_txt
cat */*/*/*/*/*/*/*.erl >> all_txt
