%Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
%1,2,3,5,8,13,21,34,55,89, ...
%By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms

: f dup integer 4000000 > if else
  dup integer 2 rem integer 0 == if 
    dup r> + >r else then
  dup tuck + recurse call
then ;

integer 0 >r 
integer 1 integer 1 f call
drop drop r>